### ISSUE TITLE
Particle effects are not scaled

### ISSUE THREAD

**Issue by pellinor0** [pellinor0/TweakScale#11]
examples: engines, stock drills

**Comment by mossarelli** [comment]
And they probably never will be unless you use RealPlumes or something similar because the PREFAB_PARTICLE node does not accept the size value as it should do and the only way to resize particle effects is to edit them in the Unity editor.

This is a problem I've spent more than 8 hours trying to fix. And the reason I'm here at this github repo is to see if tweakscale managed to find a way to rescale particle effects.

https://www.reddit.com/r/KerbalSpaceProgram/comments/44kak3/help_rescaling_enginge_plumes/

**Comment by pellinor0** [comment]
Closing this since it is nothing that TweakScale can fix
