### ISSUE TITLE
Brake torque on scaled LY-10 not saved

### ISSUE THREAD

**Issue by spiderwebby** [pellinor0/TweakScale#12]
I wondered why my spaceplane kept imploding when I touched the brakes!
It appears that the break torque setting is back to default both on VAB/SPH load and quickload ingame.

**Comment by pellinor0** [comment]
Even worse, scaling back and forth also messes up the limits of the tweakable. 

I see why the value resets. brakeTorque used not to be persistent, so TweakScale scaled the default value when loading the vessel. This can be changed by writing the exponent as "!BrakeTorque = 3". 

However, when I do this, the range of the tweakable resets on load. So all is well for shrinked parts, but the brakeTorque of enlarged parts is reduced to the original range (max 30 for the LY-10). So it looks like this solution breaks as much as it repairs. 

Btw, no idea if 3 is a good exponent for brakeTorque (imploding vessels might be a sign that it is way off). What are the scales and torque values you currently use? 

I'll see if I find some difference between "brakeTorque" and "!brakeTorque". Are there any other scaled values that are also tweakable? I can only think of resource nodes (i.e. tank contents). These are different because the max value is a kspField that is also scaled explicitely with its own exponent.

**Comment by spiderwebby** [comment]
I'm mostly using x2 scale and normally going for about 10-15. (adjusted in flight)
At x3 scale it's closer to 5.
No other tweakable parts spring to mind

**Comment by pellinor0** [comment]
Thanks for the feedback. This sounds more and more like brakeTorque does not really do what the name says. 

If the standard range is enough it might be best not to scale the value at all.

**Comment by pellinor0** [comment]
fixed by https://github.com/pellinor0/TweakScale/commit/001ec984d6367f28a7f7f14acf85b72390ad7d27 

I removed the brakeTorque exponent. The braking power seems still to scale with size, so probably the exponent was not needed anyway.
