### ISSUE TITLE
Twealscale 2.3 issue - Attach nodes wrongly placed when a downscaled part is cloned

### ISSUE THREAD

**Issue by jrodrigv** [pellinor0/TweakScale#47]
Please find enclosed a report with the steps to reproduce the issue.
[Issue Report for Tweakscale 2.3.pdf](https://github.com/pellinor0/TweakScale/files/531852/Issue.Report.for.Tweakscale.2.3.pdf)

Kind Regards and thanks for your work on this ;)

**Comment by pellinor0** [comment]
so when cloning a scaled part we have
* OnCopy: nodes are copied fine
* OnStart: still fine
* first Update: nodes are reset to the unscaled positions

That seems new. Also strange that the positions reset but the size stays scaled. 

Fixed by https://github.com/pellinor0/TweakScale/commit/02e535c9a528ee1497a8fea1418952e0993190c9. Hoping that this change has no side effects...
