### ISSUE TITLE
Support for all parts

### ISSUE THREAD

**Issue by Monniasza** [pellinor0/TweakScale#84]
Please add ability to scale all parts using only supported modules.
Ability to use TweakScale with all parts will make most scaling definitions obsolete.

**Comment by Lisias** [comment]
Hi. This fork is not currently being developed anymore, the development has been moved to 

https://github.com/net-lisias-ksp/TweakScale

I'm the new maintainer, by the way. :)

What you ask is not feasible. Each part can have different characteristics, and they need to be tackled down individually. Things appears to be easy to patch because a lot of TWEAKSCALEEXPONENTS and TWEAKSCALEBEHAVIOURS were created to make things easy on the patch file - but make no mistake, things are not that easy under the bonnet.

There's an effort to create a simplified scaling model for people that would not mind losing some fidelity in exchange for a way simpler scaling model, the Add'On [All Tweak](https://forum.kerbalspaceprogram.com/index.php?/topic/182700-14x-17x-all-tweak-06-august-3rd-2019/), a complement for TweakScale. Perhaps you would like to check it.

**Comment by Monniasza** [comment]
Moved to https://github.com/net-lisias-ksp/TweakScale/issues/78
